apiVersion: v1
kind: Service
metadata:
  name: eventservice
  namespace: default
  labels:
    app: eventservice
spec:
  type: ClusterIP
  selector:
    app: eventservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080