apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-ui
  name: kafka-ui
spec:
  type: LoadBalancer
  ports:
    - name: "7777"
      port: 7777
      targetPort: 8080
  selector:
    service: kafka-ui