apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka-ui
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka-ui
  template:
    metadata:
      labels:
        service: kafka-ui
    spec:
      containers:
        - env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafkabroker:9092
            - name: KAFKA_CLUSTERS_0_NAME
              value: SMARTFACE
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: zookeeper:2181
          image: provectuslabs/kafka-ui
          imagePullPolicy: IfNotPresent
          name: kafka-ui
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
