spring:
  application:
    name: eventservice
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
resilience4j:
  retry:
    configs:  
      default:
        maxAttempts: 2 # Varsayılan maksimum yeniden deneme sayısı
        waitDuration: 1000 # MS varsayılan bekleme süresi (1 Saniye)
    instances:
      saveEventToKafka:
        baseConfig: default
        maxAttempts: 3
      saveEventToDatabase:
        baseConfig: default
management:
  endpoint:
    health:
      access: read-only
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health